# -*- encoding: utf-8 -*-

=begin
#api

#A ruby wrapper for the Stormgate World API (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "stormgate_world_client/version"

Gem::Specification.new do |s|
  s.name        = "stormgate_world_client"
  s.version     = StormgateWorldClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = ["jleblanc@hey.com"]
  s.homepage    = "https://stormgateworld.com/"
  s.summary     = "Stormgate World API Ruby Gem"
  s.description = "A ruby wrapper for the Stormgate World API (generated by Openapi Generator https://github.com/openapitools/openapi-generator)"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
