=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::LeaderboardsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LeaderboardsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::LeaderboardsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LeaderboardsApi' do
    it 'should create an instance of LeaderboardsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::LeaderboardsApi)
    end
  end

  # unit tests for get_leaderboard
  # @param [Hash] opts the optional parameters
  # @option opts [Race] :race 
  # @option opts [Integer] :page 
  # @option opts [Integer] :count 
  # @option opts [LeaderboardOrder] :order 
  # @option opts [String] :query 
  # @return [LeaderboardResponse]
  describe 'get_leaderboard test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_leaderboard_dump
  # @param [Hash] opts the optional parameters
  # @return [LeaderboardDumpResponse]
  describe 'get_leaderboard_dump test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
