=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::LeaderboardEntriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LeaderboardEntriesApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::LeaderboardEntriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LeaderboardEntriesApi' do
    it 'should create an instance of LeaderboardEntriesApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::LeaderboardEntriesApi)
    end
  end

  # unit tests for get_leaderboard_entry_history
  # @param leaderboard_entry_id Player Leaderboard Entry ID
  # @param [Hash] opts the optional parameters
  # @return [LeaderboardEntryHistory]
  describe 'get_leaderboard_entry_history test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
