=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::PlayersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PlayersApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::PlayersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PlayersApi' do
    it 'should create an instance of PlayersApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::PlayersApi)
    end
  end

  # unit tests for get_player
  # @param player_id Player ID
  # @param [Hash] opts the optional parameters
  # @return [PlayerResponse]
  describe 'get_player test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_player_last_match
  # @param player_id Player ID
  # @param [Hash] opts the optional parameters
  # @return [MatchResponse]
  describe 'get_player_last_match test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_player_matches
  # @param player_id Player ID
  # @param [Hash] opts the optional parameters
  # @return [PlayerMatchesResponse]
  describe 'get_player_matches test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_player_preferences
  # @param player_id Player ID
  # @param [Hash] opts the optional parameters
  # @return [PlayerPreferences]
  describe 'get_player_preferences test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_player_statistics_activity
  # @param player_id Player ID
  # @param [Hash] opts the optional parameters
  # @return [PlayerActivityStats]
  describe 'get_player_statistics_activity test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_player_statistics_matchups
  # @param player_id Player ID
  # @param [Hash] opts the optional parameters
  # @return [PlayerMatchupsStats]
  describe 'get_player_statistics_matchups test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_player_statistics_opponents
  # @param player_id Player ID
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count 
  # @return [PlayerOpponentsStats]
  describe 'get_player_statistics_opponents test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_player_preferences
  # @param player_id Player ID
  # @param player_preferences 
  # @param [Hash] opts the optional parameters
  # @return [PlayerPreferences]
  describe 'update_player_preferences test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
