=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::StatisticsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StatisticsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::StatisticsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StatisticsApi' do
    it 'should create an instance of StatisticsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::StatisticsApi)
    end
  end

  # unit tests for get_statistics
  # @param [Hash] opts the optional parameters
  # @option opts [String] :league 
  # @return [StatsByTime]
  describe 'get_statistics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
