=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for StormgateWorld::ActivityStatisticsActivity
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe StormgateWorld::ActivityStatisticsActivity do
  let(:instance) { StormgateWorld::ActivityStatisticsActivity.new }

  describe 'test an instance of ActivityStatisticsActivity' do
    it 'should create an instance of ActivityStatisticsActivity' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(StormgateWorld::ActivityStatisticsActivity)
    end
  end

  describe 'test attribute "aggregated"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "history"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
