=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for StormgateWorld::CountriesStatisticsEntry
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe StormgateWorld::CountriesStatisticsEntry do
  let(:instance) { StormgateWorld::CountriesStatisticsEntry.new }

  describe 'test an instance of CountriesStatisticsEntry' do
    it 'should create an instance of CountriesStatisticsEntry' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(StormgateWorld::CountriesStatisticsEntry)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "players"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
