=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for StormgateWorld::LeaderboardEntryHistoryRow
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe StormgateWorld::LeaderboardEntryHistoryRow do
  let(:instance) { StormgateWorld::LeaderboardEntryHistoryRow.new }

  describe 'test an instance of LeaderboardEntryHistoryRow' do
    it 'should create an instance of LeaderboardEntryHistoryRow' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(StormgateWorld::LeaderboardEntryHistoryRow)
    end
  end

  describe 'test attribute "time"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "mmr"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "points"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
