=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::MatchState
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::MatchState do
  let(:instance) { OpenapiClient::MatchState.new }

  describe 'test an instance of MatchState' do
    it 'should create an instance of MatchState' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::MatchState)
    end
  end

end
