=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PlayerMatchupsStats
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PlayerMatchupsStats do
  let(:instance) { OpenapiClient::PlayerMatchupsStats.new }

  describe 'test an instance of PlayerMatchupsStats' do
    it 'should create an instance of PlayerMatchupsStats' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PlayerMatchupsStats)
    end
  end

  describe 'test attribute "cached_at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "matchups"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
