=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ProfilePrivacy
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ProfilePrivacy do
  let(:instance) { OpenapiClient::ProfilePrivacy.new }

  describe 'test an instance of ProfilePrivacy' do
    it 'should create an instance of ProfilePrivacy' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ProfilePrivacy)
    end
  end

end
