=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for StormgateWorld::ServersStatisticsEntry
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe StormgateWorld::ServersStatisticsEntry do
  let(:instance) { StormgateWorld::ServersStatisticsEntry.new }

  describe 'test an instance of ServersStatisticsEntry' do
    it 'should create an instance of ServersStatisticsEntry' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(StormgateWorld::ServersStatisticsEntry)
    end
  end

  describe 'test attribute "server"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "matches"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "players"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
