=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

# Common files
require 'stormgate_world_client/api_client'
require 'stormgate_world_client/api_error'
require 'stormgate_world_client/version'
require 'stormgate_world_client/configuration'

# Models
require 'stormgate_world_client/models/error_response'
require 'stormgate_world_client/models/leaderboard'
require 'stormgate_world_client/models/leaderboard_dump_response'
require 'stormgate_world_client/models/leaderboard_entry_history'
require 'stormgate_world_client/models/leaderboard_entry_history_entry'
require 'stormgate_world_client/models/leaderboard_entry_response'
require 'stormgate_world_client/models/leaderboard_order'
require 'stormgate_world_client/models/leaderboard_response'
require 'stormgate_world_client/models/match_participant_player_leaderboard_entry_response'
require 'stormgate_world_client/models/match_participant_player_response'
require 'stormgate_world_client/models/match_participant_response'
require 'stormgate_world_client/models/match_response'
require 'stormgate_world_client/models/match_result'
require 'stormgate_world_client/models/match_state'
require 'stormgate_world_client/models/matches_response'
require 'stormgate_world_client/models/player_activity_stats'
require 'stormgate_world_client/models/player_activity_stats_race'
require 'stormgate_world_client/models/player_matches_response'
require 'stormgate_world_client/models/player_matchups_stats'
require 'stormgate_world_client/models/player_matchups_stats_entry'
require 'stormgate_world_client/models/player_matchups_stats_matchup'
require 'stormgate_world_client/models/player_opponents_stats'
require 'stormgate_world_client/models/player_opponents_stats_opponent'
require 'stormgate_world_client/models/player_preferences'
require 'stormgate_world_client/models/player_response'
require 'stormgate_world_client/models/player_stats_entry'
require 'stormgate_world_client/models/player_stats_entry_aggregated'
require 'stormgate_world_client/models/player_stats_entry_num_breakdown'
require 'stormgate_world_client/models/profile_privacy'
require 'stormgate_world_client/models/race'
require 'stormgate_world_client/models/stats_by_time'
require 'stormgate_world_client/models/stats_by_time_entry'
require 'stormgate_world_client/models/stats_by_time_history_point'
require 'stormgate_world_client/models/stats_by_time_match_length'
require 'stormgate_world_client/models/stats_by_time_match_length_entry'

# APIs
require 'stormgate_world_client/api/leaderboard_entries_api'
require 'stormgate_world_client/api/leaderboards_api'
require 'stormgate_world_client/api/matches_api'
require 'stormgate_world_client/api/players_api'
require 'stormgate_world_client/api/statistics_api'

module StormgateWorldClient
  class << self
    # Customize default settings for the SDK using block.
    #   StormgateWorldClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
