=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'date'
require 'time'

module StormgateWorld
  class League
    ASPIRANT = "aspirant".freeze
    BRONZE = "bronze".freeze
    SILVER = "silver".freeze
    GOLD = "gold".freeze
    PLATINUM = "platinum".freeze
    DIAMOND = "diamond".freeze
    MASTER = "master".freeze

    def self.all_vars
      @all_vars ||= [ASPIRANT, BRONZE, SILVER, GOLD, PLATINUM, DIAMOND, MASTER].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if League.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #League"
    end
  end
end
