=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'date'
require 'time'

module StormgateWorld
  class Race
    INFERNALS = "infernals".freeze
    VANGUARD = "vanguard".freeze
    RANDOM = "random".freeze

    def self.all_vars
      @all_vars ||= [INFERNALS, VANGUARD, RANDOM].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if Race.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Race"
    end
  end
end
