=begin
#api

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.3.0

=end

require 'date'
require 'time'

module StormgateWorldClient
  class Leaderboard
    RANKED_1V1 = "ranked_1v1".freeze
    UNRANKED_1V1 = "unranked_1v1".freeze
    CUSTOM = "custom".freeze

    def self.all_vars
      @all_vars ||= [RANKED_1V1, UNRANKED_1V1, CUSTOM].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if Leaderboard.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Leaderboard"
    end
  end
end
